sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t franco77/react-test -f ./client/Dockerfile.dev ./client

script:
#    - docker run falcopellegrino/react-test npm test -- --coverage
    - docker run -e CI=true franco77/react-test npm test

after_success:
    - docker build -t franco77/multi-client ./client
    - docker build -t franco77/multi-nginx ./nginx
    - docker build -t franco77/multi-server ./server
    - docker build -t franco77/multi-worker ./worker
    #Log in to the docker CLI
    #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD" docker.io
    #Take those images and push them to docker hub
    - docker push franco77/multi-client
    - docker push franco77/multi-nginx
    - docker push franco77/multi-server
    - docker push franco77/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-356166853548
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY